### ISSUE TITLE
Setting About as homepage

### ISSUE THREAD

**Issue by matt-w-rees** [austingebauer/devise#1]
Hey Austin, 

After some assistance in changing the default homepage in this theme. I've removed the posts and categories options from the navigation menu and now wish to set the about page as the default homepage (you can see what I mean here - https://www.matthewreesearch.com). What is the best approach to do this?

**Comment by austingebauer** [comment]
Hi, @matt-w-rees! Sorry for the delay on responding to this issue. Let me figure out the best way to change the default homepage in the theme. I'll give you an update within the next couple of days.

**Comment by matt-w-rees** [comment]
No worries Austin - thank you so much!

**Comment by austingebauer** [comment]
@matt-w-rees - I just pushed a change to Devise (5998ca3195dfc90a6635a948674f69b569116cb0) that will allow you to set custom content on the home page.

You can do so using the following steps:
1. Pull the latest Devise theme updates into your Hugo site via the instructions in https://github.com/austingebauer/devise#updating.
2. Add a `_index.md` file into the `content` directory of your Hugo site. This will be at the path `content/_index.md`.
3. Copy/Paste the markdown contents from your about page into the new `_index.md` file you created.
4. Observe that your home page now contains the contents of your about page.

Optionally, you could remove the about page from the navigation menu and your site after it's been set as the home page.

Let me know if this works for you!

**Comment by matt-w-rees** [comment]
Worked like a charm. Thank you so much @austingebauer and also thanks for a great theme - I really love it. 

Cheers,
Matt.

**Comment by austingebauer** [comment]
Absolutely! Happy to help and glad that you like the theme. A project star would be much appreciated :)

Cheers,
Austin
