### ISSUE TITLE
Failed to get JSON resource 

### ISSUE THREAD

**Issue by akshayvijayan** [austingebauer/devise#14]
1:27:05 PM: Building sites … WARN 2021/05/15 17:57:05 Markup type mmark is deprecated and will be removed in a future release. See https://gohugo.io//content-management/formats/#list-of-content-formats
11:27:06 PM: ERROR 2021/05/15 17:57:06 Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://www.instagram.com/p/BGvuInzyFAe/&amp;maxwidth=640&amp;omitscript=true": Failed to retrieve remote file: Too Many Requests
11:27:06 PM: ERROR 2021/05/15 17:57:06 Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://www.instagram.com/p/BGvuInzyFAe/&amp;maxwidth=640&amp;omitscript=true": Failed to retrieve remote file: Too Many Requests
11:27:06 PM: Total in 1308 ms
11:27:06 PM: Error: Error building site: logged 2 error(s)
11:27:06 PM: ​
11:27:06 PM: ────────────────────────────────────────────────────────────────
11:27:06 PM:   "build.command" failed                                        
11:27:06 PM: ────────────────────────────────────────────────────────────────
11:27:06 PM: ​
11:27:06 PM:   Error message
11:27:06 PM:   Command failed with exit code 255: hugo

Which file to change for correcting the error ?

**Comment by austingebauer** [comment]
Hi @akshayvijayan - Sorry for the delay here. Did you end up resolving the issue?

**Comment by austingebauer** [comment]
Going to close this. Feel free to reopen!
