### ISSUE TITLE
How to set about as the homepage? And the HTML syntax seems to be ineffective

### ISSUE THREAD

**Issue by YuanJ2003** [austingebauer/devise#30]
May I ask how to set the about page as the homepage like your homepage? My default has always been the posts page.And the HTML syntax seems to be ineffective.

**Comment by austingebauer** [comment]
Hi @YuanJ2003! I put an `_index.md` page in the top-level `content` directory which includes the content for my home page. Were you able to try that?

**Comment by YuanJ2003** [comment]
Thank you! I modified the code of index.html and It solved the question.

```html
{{ define "main" }}
    {{- with .Site.GetPage "about" -}}
        <div class="pl-sm-4 ml-sm-5">
            {{ .Content }}
        </div>
    {{- end -}}
{{ end }}
```

**Comment by austingebauer** [comment]
Glad you were able to get it fixed. I'm going to close this issue 👍
