### ISSUE TITLE
Is there a way to add image in post/content?

### ISSUE THREAD

**Issue by kingcaubalejo** [austingebauer/devise#34]

**Comment by austingebauer** [comment]
You should be able to use markdown image format like:

```md
![](https://your.image.url/your-image.jpg)
```

Or HTML like:
```html
<img class="" src="/images/your-image.png"/>
```

**Comment by kingcaubalejo** [comment]
Alright, thanks Austin.

By the way, thanks for this theme it's really awesome.
Below is my blogpost using your theme.

https://kingcaubalejo.github.io/dlowblog/post/

**Comment by austingebauer** [comment]
@kingcaubalejo - Awesome, glad you like it. A project ⭐ is always appreciated.
