### ISSUE TITLE
Blockquote indentation

### ISSUE THREAD

**Issue by karthiktadepalli1** [austingebauer/devise#8]
Thanks for making such a lovely theme! My only issue is that blockquotes aren't indented or styled in any way by default, and I have to add custom CSS to do that. It seems like blockquotes should be indented by default.

**Comment by austingebauer** [comment]
Thank you, @karthiktadepalli1! I like what you've done with the blockquotes on your website. Looks great 👍 

I'll fix this up some that blockquotes are indented by default.

**Comment by austingebauer** [comment]
Default blockquote styles are included in the master branch of the theme now.

I've also included an easier way to add custom CSS styles (if you're interested) via Hugo pipes. You can find the instructions here: https://github.com/austingebauer/devise#option-2

Thanks again for opening the issue!
